package com.example.intent.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StoreManagerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoreManagerAllPropertiesEquals(StoreManager expected, StoreManager actual) {
        assertStoreManagerAutoGeneratedPropertiesEquals(expected, actual);
        assertStoreManagerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoreManagerAllUpdatablePropertiesEquals(StoreManager expected, StoreManager actual) {
        assertStoreManagerUpdatableFieldsEquals(expected, actual);
        assertStoreManagerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoreManagerAutoGeneratedPropertiesEquals(StoreManager expected, StoreManager actual) {
        assertThat(actual)
            .as("Verify StoreManager auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoreManagerUpdatableFieldsEquals(StoreManager expected, StoreManager actual) {
        assertThat(actual)
            .as("Verify StoreManager relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoreManagerUpdatableRelationshipsEquals(StoreManager expected, StoreManager actual) {
        // empty method
    }
}
